// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/classroom": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/classroom";
  };
  "./pages/Students.page.tsx": {
    id: "pages/Students.page";
    page: "/";
  };
  "./pages/Classroom.page.tsx": {
    id: "pages/Classroom.page";
    page: "/classroom";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/Students.page": typeof import("./src/./pages/Students.page.tsx");
  "pages/Classroom.page": typeof import("./src/./pages/Classroom.page.tsx");
};